---
- hosts: vsrx
  gather_facts: no
  connection: local
  
  tasks:
    - name: set
      junos_config:
        lines:
          - ******
        provider: "{{ cli }}"

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

