---
- hosts: vsrx
  gather_facts: no
  connection: local
  
  tasks:
    - name: set
      junos_config:
        src: ********************
        src_format: set
        provider: "{{ cli }}"
      register: result

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

